/**
 * Integration tests for anonymous attestation verification with real
 * pseudonym-bound proofs generated by bbs-ffi.
 */

import { describe, it, expect, beforeEach } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  AnonymousAttestationVerifier,
  type AnonymousAttestation,
  type AttestationSecurityType,
  type ApproverDeviceType,
} from "../attestation.js";
import { NullifierStore } from "../nullifier-store.js";

/** Fixture shape for the bbs-ffi-generated pseudonym vector. */
type PseudonymVector = {
  issuerPublicKeyHex: string;
  proofHex: string;
  pseudonymHex: string;
  headerHex: string;
  presentationHeaderHex: string;
  scopeHex: string;
  totalSignerMessages: number;
  disclosedMessages: Array<{
    index: number;
    valueHex: string;
  }>;
};

/** Convert hex string to bytes. */
function hexToBytes(hex: string): Uint8Array {
  return new Uint8Array(Buffer.from(hex, "hex"));
}

/** Decode int64 big-endian bytes into a JS number. */
function decodeInt64BigEndian(bytes: Uint8Array): number {
  let value = 0n;
  for (const byte of bytes) {
    value = (value << 8n) | BigInt(byte);
  }
  return Number(value);
}

/** Load the canonical pseudonym verification vector fixture. */
function loadPseudonymVector(
  fixtureFile = "bbs-pseudonym-vector.json",
): PseudonymVector {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const fixturePath = path.join(here, "fixtures", fixtureFile);
  const raw = fs.readFileSync(fixturePath, "utf8");
  return JSON.parse(raw) as PseudonymVector;
}

/** Build a valid AnonymousAttestation from the vector fixture. */
function makeAttestation(vector: PseudonymVector): AnonymousAttestation {
  const disclosedMap = new Map<number, Uint8Array>(
    vector.disclosedMessages.map((message) => [
      message.index,
      hexToBytes(message.valueHex),
    ]),
  );

  const scope = new TextDecoder().decode(hexToBytes(vector.scopeHex));
  const attestationType = new TextDecoder().decode(
    disclosedMap.get(0) as Uint8Array,
  ) as AttestationSecurityType;
  const deviceType = new TextDecoder().decode(
    disclosedMap.get(1) as Uint8Array,
  ) as ApproverDeviceType;

  return {
    bbsProof: hexToBytes(vector.proofHex),
    pseudonym: hexToBytes(vector.pseudonymHex),
    scope,
    presentationHeader: hexToBytes(vector.presentationHeaderHex),
    revealedMessages: {
      attestationType,
      deviceType,
      expiresAt: decodeInt64BigEndian(disclosedMap.get(3) as Uint8Array),
    },
  };
}

describe("Anonymous Attestation Integration (cryptographic pseudonym verification)", () => {
  let verifier: AnonymousAttestationVerifier;
  const vector = loadPseudonymVector();
  const androidVector = loadPseudonymVector(
    "android-bbs-pseudonym-vector.json",
  );
  const issuerPublicKey = hexToBytes(vector.issuerPublicKeyHex);
  const androidIssuerPublicKey = hexToBytes(androidVector.issuerPublicKeyHex);

  beforeEach(() => {
    verifier = new AnonymousAttestationVerifier();
  });

  it("verifies a real pseudonym-bound proof from bbs-ffi", async () => {
    const attestation = makeAttestation(vector);

    const result = await verifier.verify(attestation, {
      issuerPublicKey,
      expectedRequestId: attestation.scope,
    });

    expect(result.valid).toBe(true);
    expect(result.proofValid).toBe(true);
    expect(result.pseudonymVerified).toBe(true);
    expect(result.notExpired).toBe(true);
    expect(result.scopeValid).toBe(true);
    expect(result.errors).toHaveLength(0);
  });

  it("verifies an Android-format pseudonym-bound proof", async () => {
    const attestation = makeAttestation(androidVector);

    const result = await verifier.verify(attestation, {
      issuerPublicKey: androidIssuerPublicKey,
      expectedRequestId: attestation.scope,
    });

    expect(result.valid).toBe(true);
    expect(result.proofValid).toBe(true);
    expect(result.pseudonymVerified).toBe(true);
    expect(result.notExpired).toBe(true);
    expect(result.scopeValid).toBe(true);
    expect(result.errors).toHaveLength(0);
  });

  it("fails when issuer public key is wrong", async () => {
    const attestation = makeAttestation(vector);
    const wrongIssuerPublicKey = new Uint8Array(issuerPublicKey);
    wrongIssuerPublicKey[0] ^= 0xff;

    const result = await verifier.verify(attestation, {
      issuerPublicKey: wrongIssuerPublicKey,
    });

    expect(result.valid).toBe(false);
    expect(result.proofValid).toBe(false);
  });

  it("fails when proof is tampered", async () => {
    const attestation = makeAttestation(vector);
    const tamperedProof = new Uint8Array(attestation.bbsProof);
    tamperedProof[0] ^= 0xff;
    tamperedProof[10] ^= 0xff;

    const result = await verifier.verify(
      {
        ...attestation,
        bbsProof: tamperedProof,
      },
      { issuerPublicKey },
    );

    expect(result.valid).toBe(false);
    expect(result.proofValid).toBe(false);
  });

  it("fails when pseudonym is tampered", async () => {
    const attestation = makeAttestation(vector);
    const tamperedPseudonym = new Uint8Array(attestation.pseudonym);
    tamperedPseudonym[4] ^= 0xff;

    const result = await verifier.verify(
      {
        ...attestation,
        pseudonym: tamperedPseudonym,
      },
      { issuerPublicKey },
    );

    expect(result.valid).toBe(false);
    expect(result.proofValid).toBe(false);
  });

  it("fails when revealed messages are tampered", async () => {
    const attestation = makeAttestation(vector);

    const result = await verifier.verify(
      {
        ...attestation,
        revealedMessages: {
          ...attestation.revealedMessages,
          attestationType: "android_strongbox",
        },
      },
      { issuerPublicKey },
    );

    expect(result.valid).toBe(false);
    expect(result.proofValid).toBe(false);
  });

  it("rejects replay for same scope when NullifierStore is used", async () => {
    const attestation = makeAttestation(vector);
    const nullifierStore = new NullifierStore("test-integration-pseudonyms");

    const options = {
      issuerPublicKey,
      nullifierStore,
    };

    const first = await verifier.verify(attestation, options);
    expect(first.valid).toBe(true);

    const second = await verifier.verify(attestation, options);
    expect(second.valid).toBe(false);
    expect(second.errors).toContain("pseudonym already used for this scope");
  });
});
